server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cafemood
    username: dev
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: cafeMood
logging:
  level:
    root: INFO
admin:
  id: admin
  password: ""