server:
  servlet:
    context-path: /api
  port: 8080
spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/cafemood
    username: dev
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: cafeMood
logging:
  level:
    root: INFO
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
admin:
  id: admin
  password: ""